package consts

const StockService = "service.stock"
const StockController = "controller.stock"
const StockRepository = "repository.stock"
const StockCacheRepository = "cache.stock"

const StockTable = "stocks"
const StockFieldOwnerID = "owner_id"
const StockFieldID = "id"
const StockFieldCategoryID = "category_id"
const StockFieldLocationID = "location_id"
const StockFieldGroupItemID = "group_item_id"
const StockFieldUnitID = "unit_id"
const TypeNonInventory = "non-inventory"
const TypeInventory = "inventory"
const RecordTypeStock = "stock"
const RecordTypeProduct = "product"
const StockFieldSKU = "sku"
const StockFieldName = "name"
const StockFieldType = "type"
const StockFieldRecordType = "record_type"
const StockFieldExpiryDate = "expiry_date"
const StockFieldStatus = "status"
const StockInactiveStatus = "inactive"
const StockActiveStatus = "active"
const StockFieldSellingPrice = "selling_price"
const StockFieldPurchasePrice = "purchase_price"
const StockFieldDescription = "description"

const StockInventoryType = "inventory"
const StockNoninventoryType = "non-inventory"

const WarehouseFieldTitle = "warehouses.title"
const UnitTableFieldTitle = "units.title"
const StockFieldAccountID = "account_id"
const ModelNameAddStockRequestBody = "AddStockRequestBody"
const ModelNameUpdateStockRequestBody = "UpdateStockRequestBody"
